##source("best.R") ; best("TX", "heart attack")
##source("rankall.R") ; head(rankall("heart attack", 20), 10)
##source("rankall.R") ;tail(rankall("pneumonia", "worst"), 3)
##source("rankall.R") ;tail(rankall("heart failure"), 10)
##source("rankhospital.R") ;rankhospital("MN", "heart attack", 5000)
##source("rankhospital.R"); rankhospital("MD", "heart attack", "worst")
##source("rankhospital.R"); rankhospital("TX", "heart failure", 4)
##source("best.R") ;best("SC", "heart attack")
##source("best.R") ;best("NY", "pneumonia")
##source("best.R") ;best("AK", "pneumonia")
##source("rankhospital.R") ;rankhospital("NC", "heart attack", "worst")
##source("rankhospital.R") ;rankhospital("WA", "heart attack", 7)
##source("rankhospital.R") ;rankhospital("TX", "pneumonia", 10)
##source("rankhospital.R") ;rankhospital("NY", "heart attack", 7)
##source("rankall.R") ; r <- rankall("heart attack", 4) 
##as.character(subset(r, state == "HI")$hospital)
##source("rankall.R") ; r <- rankall("pneumonia", "worst") 
##as.character(subset(r, state == "NJ")$hospital)
source("rankall.R") ; r <- rankall("heart failure", 10)
as.character(subset(r, state == "NV")$hospital)